### ISSUE TITLE
Depedency..

### ISSUE THREAD

**Issue by tbnritzdoge** [BajanVlogs/RulesUI#1]
Does this depend on the PMMP Official UI branch?

**Comment by XDqrkneZ** [comment]
obviously no

**Comment by OfficialLilKev** [comment]
Yes it does

**Comment by XDqrkneZ** [comment]
deleted my comment "obviously not"? You must be sick https://github.com/BajanVlogs/RulesUI/blob/ed7eb27f127654af4e4cdb0dc80032f565624500/src/RulesUI/Main.php#L18
